name: reusable-deploy-tag-flow

on:
  workflow_call:
    inputs:
      slack_channel_id:
        required: false
        type: string
      app_name:
        required: true
        type: string
      service_name:
        required: false
        type: string
      deploy_service:
        required: false
        type: string
      deploy_task:
        required: false
        type: string
      deploy_registry:
        required: false
        type: string
      deploy_repo:
        required: false
        type: string
      deploy_cluster:
        required: false
        type: string
        default: private
      deploy_tag:
        description: 'Tag to be deployed'
        required: false
        type: string

    secrets:
      aws_ca_domain:
        description: 'AWS_CA_DOMAIN'
        required: false
      aws_ca_owner_id:
        description: 'AWS_CA_OWNER_ID'
        required: false
      aws_role_to_assume:
        description: 'AWS_ROLE_TO_ASSUME'
        required: false
      slack_bot_token:
        description: 'SLACK_BOT_TOKEN'
        required: false
      cd_token:
        description: 'CD_TOKEN'
        required: false

jobs:
  Build:
    runs-on: ubuntu-latest

    environment: TEST

    steps:
      - name: "Setup: Checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Setup: Set tag to deploy from input"
        if: ${{ inputs.deploy_tag != 0 }}
        run: |
          echo "DEPLOY_TAG=${{ inputs.deploy_tag }}" >> $GITHUB_ENV

      - name: "Setup: Get latest tag if input is empty"
        if: ${{ inputs.deploy_tag == 0 }}
        run: |
          echo "DEPLOY_TAG=$(git tag --sort=committerdate | tail -1)" >> $GITHUB_ENV

      - name: "Setup: Set task name to deploy from input"
        if: ${{ inputs.deploy_task != 0 }}
        run: |
          echo "DEPLOY_TASK=${{ inputs.deploy_task }}" >> $GITHUB_ENV

      - name: "Setup: Create default task name if input is empty"
        if: ${{ inputs.deploy_task == 0 }}
        run: |
          echo "DEPLOY_TASK=softpos-${{ inputs.app_name }}-task" >> $GITHUB_ENV

      - name: "Setup: Set service name to deploy from input"
        if: ${{ inputs.deploy_service != 0 }}
        run: |
          echo "DEPLOY_SERVICE=${{ inputs.deploy_service }}" >> $GITHUB_ENV

      - name: "Setup: Create default service name to deploy if input is empty"
        if: ${{ inputs.deploy_service == 0 }}
        run: |
          echo "DEPLOY_SERVICE=${{ inputs.service_name }}" >> $GITHUB_ENV

      - name: "Setup: Set image registry name to deploy from input"
        if: ${{ inputs.deploy_registry != 0 }}
        run: |
          echo "DEPLOY_REGISTRY=${{ inputs.deploy_registry }}" >> $GITHUB_ENV

      - name: "Setup: Create default image registry name to deploy if input is empty"
        if: ${{ inputs.deploy_service == 0 }}
        run: |
          echo "DEPLOY_REGISTRY=${{ inputs.service_name }}" >> $GITHUB_ENV

      - name: "Release: Check if a github release already exists"
        id: find_release
        run: |
          get_release_tag_command=$(curl -s -o /dev/null -I -w "%{http_code}" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "${{ github.api_url }}/repos/${{ github.repository }}/releases/tags/${{ env.DEPLOY_TAG }}")
          if [ $get_release_tag_command -eq 200 ] ; then
            echo "tag release already exists"
            echo "::set-output name=release_tag_exist::0"
          elif [ $get_release_tag_command -eq 404 ] ; then
            echo "tag release does not exists"
            echo "::set-output name=release_tag_exist::1"
          else 
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Release: Get latest github release"
        if: ${{ steps.find_release.outputs.release_tag_exist != 0 }}
        run: |
          echo "LATEST_GH_RELEASE=$(gh api repos/meawallet/${{ github.event.repository.name }}/releases/latest --jq '.name' |  awk '{print substr($1,9)}')" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Release: Bump github release version"
        id: bump_gh_release_version
        if: ${{ steps.find_release.outputs.release_tag_exist != 0 }}
        uses: christian-draeger/increment-semantic-version@1.0.2
        with:
          current-version: ${{ env.LATEST_GH_RELEASE }}
          version-fragment: 'bug'

      - name: "Release: Create new github release version"
        id: gh_new_release
        if: ${{ steps.find_release.outputs.release_tag_exist != 0 }}
        run: |
          gh release create ${{ env.DEPLOY_TAG }} -t release-${{ steps.bump_gh_release_version.outputs.next-version }} --generate-notes
          release_json=$(gh api repos/meawallet/${{ github.event.repository.name }}/releases/tags/${{ env.DEPLOY_TAG }})
          release_title=$(jq -r '.name' <<< "$release_json")
          echo "::set-output name=release_title::$release_title"
          release_body=$(jq '.body' <<< "$release_json")
          echo "::set-output name=release_body::$release_body"
          release_url=$(jq -r '.html_url' <<< "$release_json")
          echo "::set-output name=release_url::$release_url"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Release: Notify Slack release notes"
        id: slack-post-release
        if: ${{ steps.find_release.outputs.release_tag_exist != 0 }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.slack_bot_token }}
        uses: slackapi/slack-github-action@v1.21.0
        with:
          channel-id: meapay-acquiring-team-test
          payload: |
            {
              "text": "${{ steps.gh_new_release.outputs.release_title }}",
              "blocks":
              [
                {
                  "type": "header",
                  "text":
                    {
                      "type": "plain_text",
                      "text": ":meapay: ${{ steps.gh_new_release.outputs.release_title }}"
                    }
                },
                {
                  "type": "section",
                  "text":
                    {
                      "type": "mrkdwn",
                      "text": ${{ steps.gh_new_release.outputs.release_body }}
                    },                
                    "accessory": {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "Check on Github :github:",
                        "emoji": true
                      },
                      "url": "${{ steps.gh_new_release.outputs.release_url }}",
                      "action_id": "button-action"
                    }
                }
              ]
            }

      - name: "Setup: Setup AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.aws_role_to_assume }}
          aws-region: eu-central-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: "Deploy: Dispatch deployment to tst environment"
        if: ${{ success() && env.DEPLOY_SERVICE != 0 && inputs.deploy_repo != 0 }}
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.cd_token }}
          event-type: tst-release
          client-payload: '{"app_name": "${{ inputs.app_name }}", "service_name": "${{ env.DEPLOY_SERVICE }}", "task_name": "${{ env.DEPLOY_TASK }}", "registry_name": "${{ env.DEPLOY_REGISTRY }}", "image_version": "${{ steps.version.outputs.version_tag }}", "repository": "${{ github.repository }}", "run_id": "${{ github.run_id }}", "cluster": "${{ inputs.deploy_cluster }}"}'
          repository: ${{ inputs.deploy_repo }}

      - name: "Deploy: Notify Slack errors"
        id: slack
        if: ${{ failure() && inputs.slack_channel_id != 0 }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.slack_bot_token }}
        uses: slackapi/slack-github-action@v1.21.0
        with:
          channel-id: ${{ inputs.slack_channel_id }}
          slack-message: Pipeline failed *${{ github.workflow }}* ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
